### ISSUE TITLE
Training fails with import error

### ISSUE THREAD

**Issue by Mehedi1997** [sachindroid8/self-driving-car-using-google-colab#1]
Hi, can you please help me, when I execute this line of code in colab `!python /content/d2/manage.py train --model /content/d2/models/mypilot.h5` I get the following error message 

 loading config file: /content/d2/config.py
loading personal config over-rides

config loaded
Traceback (most recent call last):
  File "/content/d2/manage.py", line 575, in <module>
    from train import multi_train, preprocessFileList
  File "/content/d2/train.py", line 36, in <module>
    from donkeycar.parts.keras import KerasLinear, KerasIMU,\
  File "/content/donkey/donkeycar/parts/keras.py", line 18, in <module>
    from tensorflow import ConfigProto, Session
ImportError: cannot import name 'ConfigProto'

**Comment by sachindroid8** [comment]
Please provide more information. What version of TensorFlow, python version, etc. Have you prepared the data folder, etc?

**Comment by sachindroid8** [comment]
> Hi, can you please help me, when I execute this line of code in colab `!python /content/d2/manage.py train --model /content/d2/models/mypilot.h5` I get the following error message
> 
> loading config file: /content/d2/config.py
> loading personal config over-rides
> 
> config loaded
> Traceback (most recent call last):
> File "/content/d2/manage.py", line 575, in 
> from train import multi_train, preprocessFileList
> File "/content/d2/train.py", line 36, in 
> from donkeycar.parts.keras import KerasLinear, KerasIMU,
> File "/content/donkey/donkeycar/parts/keras.py", line 18, in 
> from tensorflow import ConfigProto, Session
> ImportError: cannot import name 'ConfigProto'

Please provide more information. What version of TensorFlow, python version, etc. Have you prepared the data folder, etc?
